name: simple_gql
description: A minimal library to do GraphQL queries and mutations (subscriptions not handled)
version: 1.2.0
homepage: https://github.com/lecuivre-alban/simple_gql

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.1
  meta: ^1.3.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
